### ISSUE TITLE
It's a good idea to try to simplify the CSS code when possible.

### ISSUE THREAD

**Issue by josephtkim** [kolsonperc/prj-rev-bwfs-dasmoto#6]
Great job simplifying the CSS by applying the font-family to the universal selector. However, it is a good idea to try and simplify the CSS code as much as possible to make the code cleaner and to remove repetitive code. You can simplify your CSS further by applying some other shared properties to the elements along with what you have so far. 

```css
* {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 32px;
  color: white;
}
```
